### ISSUE TITLE
English language syntax

### ISSUE THREAD

**Issue by Flannana** [Vampyr7878/TransmogOutfits#3]
## Description
When deleting an outfit, the sentence being displayed does not make sense and has a spelling error. See below screenshot.

A suggested edit to this could be:
"Do you really want to remove outfit named"
or
"Are you sure you want to remove this outfit?"

## Screenshot
![image](https://github.com/user-attachments/assets/9af82042-b650-4198-a7ed-c04e963eaf63)

**Comment by Vampyr7878** [comment]
Both errors are just typos. Sometimes it happens to me that I omit a word by accident in writing. I will fix it with the next update.
